MyDoList/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("", include("tasks.urls", namespace="tasks")),
]

tasks/urls.py
from django.urls import path

from tasks.views import (
    UserRegistrationView,
    TaskListView,
    TaskCreateView,
    TaskDeleteView,
    TaskUpdateView,
    TagCreateView,
    TagListView,
    TagDeleteView,
    TagUpdateView,
    complete_task_or_uncompleted,
)

urlpatterns = [
    path("register/", UserRegistrationView.as_view(), name="register-user"),
    path("", TaskListView.as_view(), name="my-tasks"),
    path("add-task/", TaskCreateView.as_view(), name="add-task"),
    path(
        "delete-task/<int:pk>/", TaskDeleteView.as_view(), name="delete-task"
    ),
    path(
        "update-task/<int:pk>/", TaskUpdateView.as_view(), name="update-task"
    ),
    path("add-tag", TagCreateView.as_view(), name="add-tag"),
    path("tag-list/", TagListView.as_view(), name="tag-list"),
    path("delete-tag/<int:pk>/", TagDeleteView.as_view(), name="delete-tag"),
    path("update-tag/<int:pk>/", TagUpdateView.as_view(), name="update-tag"),
    path(
        "toggle-task-assign/<int:pk>/",
        complete_task_or_uncompleted,
        name="toggle-task-assign",
    ),
]

app_name = "tasks"

tasks/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    pass


class Tag(models.Model):
    name = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Tag"
        verbose_name_plural = "Tags"


class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=64)
    description = models.TextField(max_length=255, null=True, blank=True)
    deadline = models.DateTimeField(null=True, blank=True)
    at_created = models.DateTimeField(auto_now_add=True)
    tags = models.ManyToManyField(Tag, related_name="tasks")
    is_done = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["is_done", "-at_created"]
        verbose_name = "Task"
        verbose_name_plural = "Tasks"

tasks/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms

from tasks.models import User, Task, Tag


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = UserCreationForm.Meta.fields


class TaskCreateForm(forms.ModelForm):
    deadline = forms.DateTimeField(
        widget=forms.widgets.DateTimeInput(attrs={"type": "datetime-local"}),
        required=False,
    )

    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = Task
        fields = (
            "name",
            "description",
            "deadline",
            "tags",
        )

tasks/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpRequest, HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, DeleteView

from tasks.forms import UserRegistrationForm, TaskCreateForm
from tasks.models import Task, User, Tag


class UserRegistrationView(CreateView):
    model = User
    form_class = UserRegistrationForm
    template_name = "registration/register_form.html"

    success_url = reverse_lazy("tasks:login")


class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = "tasks/task_list.html"

    def get_queryset(self):
        return Task.objects.filter(
            user=self.request.user
        ).prefetch_related("tags")


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    template_name = "tasks/task_form.html"
    form_class = TaskCreateForm

    success_url = reverse_lazy("tasks:my-tasks")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(TaskCreateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["referer"] = self.request.META.get("HTTP_REFERER")
        context["is_update"] = False

        return context


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    template_name = "tasks/task_form.html"
    form_class = TaskCreateForm

    success_url = reverse_lazy("tasks:my-tasks")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["referer"] = self.request.META.get("HTTP_REFERER")
        context["is_update"] = True

        return context


class TaskDeleteView(LoginRequiredMixin, DeleteView):
    model = Task
    template_name = "tasks/task_confirm_delete.html"
    success_url = reverse_lazy("tasks:my-tasks")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["referer"] = self.request.META.get("HTTP_REFERER")

        return context


class TagCreateView(LoginRequiredMixin, CreateView):
    model = Tag
    template_name = "tasks/tag_form.html"
    fields = ("name",)

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(TagCreateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["referer"] = self.request.META.get("HTTP_REFERER")

        return context

    def get_success_url(self):
        next_url = self.request.GET.get("next")
        if next_url:
            return next_url
        return reverse_lazy("tasks:my-tasks")


class TagUpdateView(LoginRequiredMixin, UpdateView):
    model = Tag
    template_name = "tasks/tag_form.html"
    fields = ("name",)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["referer"] = self.request.META.get("HTTP_REFERER")
        context["is_update"] = True

        return context

    def get_success_url(self):
        next_url = self.request.GET.get("next")
        if next_url:
            return next_url
        return reverse_lazy("tasks:tag-list")


class TagDeleteView(LoginRequiredMixin, DeleteView):
    model = Tag
    template_name = "tasks/tag_confirm_delete.html"
    success_url = reverse_lazy("tasks:tag-list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["referer"] = self.request.META.get("HTTP_REFERER")

        return context


class TagListView(LoginRequiredMixin, ListView):
    model = Tag
    template_name = "tasks/tag_list.html"

    def get_queryset(self):
        return Tag.objects.filter(user=self.request.user)


@login_required
def complete_task_or_uncompleted(
        request: HttpRequest,
        pk: int
) -> HttpResponseRedirect:
    task = get_object_or_404(Task, id=pk, user=request.user)
    task.is_done = not task.is_done
    task.save()

    next_url = request.GET.get("next")
    if next_url:
        return HttpResponseRedirect(next_url)
    return HttpResponseRedirect(reverse_lazy("tasks:my-tasks"))

templates/includes/navigation-fullscreen.html
<nav id="navbar-main"
     class="navbar navbar-horizontal navbar-transparent navbar-main navbar-expand-lg navbar-light">
  <div class="container">
    <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbar-collapse" aria-controls="navbar-collapse"
            aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse navbar-custom-collapse collapse"
         id="navbar-collapse">
      <div class="navbar-collapse-header">
        <div class="row">
          <div class="col-6 collapse-brand">
          </div>
          <div class="col-6 collapse-close">
            <button type="button" class="navbar-toggler" data-toggle="collapse"
                    data-target="#navbar-collapse"
                    aria-controls="navbar-collapse" aria-expanded="false"
                    aria-label="Toggle navigation">
              <span></span>
              <span></span>
            </button>
          </div>
        </div>
      </div>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          {% if user.is_authenticated %}
            <form method="post" action="{% url 'logout' %}">
              {% csrf_token %}
              <button type="submit" class="btn btn-link nav-link">LogOut
              </button>
            </form>
          {% else %}
            <a href="{% url 'login' %}" class="nav-link">
              <span class="nav-link-inner--text">Login</span>
            </a>
          {% endif %}
        </li>
        <li class="nav-item">
          {% if not user.is_authenticated %}
          <a href="{% url 'tasks:register-user' %}" class="nav-link">
            <span class="nav-link-inner--text">Register</span>
          </a>
          {% endif %}
        </li>
      </ul>
      <hr class="d-lg-none"/>
      </ul>
    </div>
  </div>
</nav>

templates/includes/scripts.html
  <script src="/static/assets/vendor/jquery/dist/jquery.min.js"></script>
  <script src="/static/assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <script src="/static/assets/vendor/js-cookie/js.cookie.js"></script>
  <script src="/static/assets/vendor/jquery.scrollbar/jquery.scrollbar.min.js"></script>
  <script src="/static/assets/vendor/jquery-scroll-lock/dist/jquery-scrollLock.min.js"></script>

templates/includes/sidenav.html
<nav
    class="sidenav navbar navbar-vertical  fixed-left  navbar-expand-xs navbar-light bg-white"
    id="sidenav-main">
  <div class="scrollbar-inner">
    <!-- Brand -->
    <div class="navbar-inner">
      <!-- Collapse -->
      <div class="collapse navbar-collapse" id="sidenav-collapse-main">
        <!-- Nav items -->
        <ul class="navbar-nav">
        <li class="nav-item">
{#              <i class="ni ni-single-02 text-orange"></i>#}
              <span class="nav-link-text">
                <strong>Hello, {{ request.user }}!</strong>
              </span>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if 'icons' in segment %} active {% endif %}"
               href="{% url 'tasks:my-tasks' %}">
              <i class="ni ni-single-02 text-orange"></i>
              <span class="nav-link-text">My tasks</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if 'tables' in segment %} active {% endif %}"
               href="{% url 'tasks:tag-list' %}">
              <i class="ni ni-bullet-list-67 text-default"></i>
              <span class="nav-link-text">Tags</span>
            </a>
          </li>
        </ul>

        <hr class="my-3">
        <form method="post" action="{% url 'logout' %}">
          {% csrf_token %}
          <a class="nav-link">
            <div class="d-flex align-items-center">
              <i class="ni ni-user-run text-red ml-2"></i>
              <input class="dropdown-item" type="submit" value="Logout">
            </div>
          </a>
        </form>
      </div>
    </div>
  </div>
</nav>

templates/includes/task_card.html
<div class="card" style="width: 22rem;">
  <div class="card-body">
    <h2 class="card-title">{{ task.name }}
      {% if task.is_done %}
        <span style="color: #00BB33">Done</span>
      {% else %}
        <span style="color: #FF0000">Not done</span>
      {% endif %}
    </h2>
    <p class="card-text">{{ task.description }}</p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">
      <strong>Created:</strong> {{ task.at_created|date:"Y, F j H:i" }}
    </li>
    <li class="list-group-item">
      <strong>Deadline:</strong> {{ task.deadline|date:"Y, F j H:i" }}
    </li>
    <li class="list-group-item">
      <strong>Tags:</strong> {{ task.tags.all|join:", " }}
    </li>
  </ul>
  <div class="card-body">
    <a href="{% url 'tasks:update-task' task.id %}?next={{ request.path }}"
       class="btn btn-outline-primary">
      Edite
    </a>
    <a href="{% url 'tasks:delete-task' task.id %}?next={{ request.path }}"
       class="btn btn-outline-danger">
      Delete
    </a>
    {% if task.is_done %}
      <a href="{% url 'tasks:toggle-task-assign' task.id %}?next={{ request.path }}"
         class="btn btn-secondary">
        Undo
      </a>
    {% else %}
      <a href="{% url 'tasks:toggle-task-assign' task.id %}?next={{ request.path }}"
         class="btn btn-success">
        Complete
      </a>
    {% endif %}
  </div>
</div>

templates/layouts/base-fullscreen.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8"/>
  <meta name="viewport"
        content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="canonical"
        href="https://appseed.us/admin-dashboards/django-dashboard-argon">

  <title>
    {% block title %}CAD.Project System{% endblock %}
  </title>

  <link rel="icon" href="/static/img/cad_icon.png"
        type="image/png">
  <!-- Fonts -->
  <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700">
  <!-- Icons -->
  <link rel="stylesheet" href="/static/assets/vendor/nucleo/css/nucleo.css"
        type="text/css">
  <link rel="stylesheet"
        href="/static/assets/vendor/@fortawesome/fontawesome-free/css/all.min.css"
        type="text/css">
  <!-- Argon CSS -->
  <link rel="stylesheet" href="/static/assets/css/argon.css?v=1.2.0"
        type="text/css">

  <!-- Specific CSS goes HERE -->
  {% block stylesheets %}{% endblock stylesheets %}

</head>

<body class="bg-default">

<div class="main-content">

  {% include "includes/navigation-fullscreen.html" %}
  {% load static %}

  
  <!-- Header -->
  <div class="header bg-gradient-primary py-7 py-lg-8">
    {% block header_container %}
    <div class="container">
      <div class="header-body text-center mb-7">
        <div class="row justify-content-center">
          <div class="col-lg-5 col-md-6">
            <div class="text-center">
              <img class="mb-4" src="{% static 'img/cad_icon.png' %}" alt=""
                   width="65" height="65">
            </div>
            <h1 class="text-white"
                style="font-family: Arial, sans-serif; font-weight: bold">
              CAD.Project System
            </h1>
            <p class="text-lead text-light">
              System for managing CAD projects and organizing the work of
              project teams.
            </p>
          </div>
        </div>
      </div>
    </div>
    
    {% endblock header_container %}

    <div class="separator separator-bottom separator-skew zindex-100">
      <svg x="0" y="0" viewBox="0 0 2560 100" preserveAspectRatio="none"
           version="1.1" xmlns="http://www.w3.org/2000/svg">
        <polygon class="fill-default" points="2560 0 2560 100 0 100"></polygon>
      </svg>
    </div>
  </div>

  {% block content %}

  {% endblock content %}


</div>

{% include "includes/scripts.html" %}

<!-- Specific JS goes HERE -->
{% block javascripts %}{% endblock javascripts %}

<script src="/static/assets/js/argon.js?v=1.2.0"></script>

</body>

</html>

templates/layouts/base.html
<!--
=========================================================
* Argon Dashboard - v1.2.0
=========================================================
* Product Page: https://www.creative-tim.com/product/argon-dashboard


* Copyright  Creative Tim (http://www.creative-tim.com)
* Coded by www.creative-tim.com



=========================================================
* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
-->
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8"/>
  <meta name="viewport"
        content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="canonical"
        href="https://appseed.us/admin-dashboards/django-dashboard-argon">

  <title>
    {% block title %} MyDoList {% endblock %}
  </title>


  <!-- Favicon - loaded as static -->
  <!-- Fonts -->
  <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700">
  <!-- Icons -->
  <link rel="stylesheet" href="/static/assets/vendor/nucleo/css/nucleo.css"
        type="text/css">
  <link rel="stylesheet"
        href="/static/assets/vendor/@fortawesome/fontawesome-free/css/all.min.css"
        type="text/css">
  <!-- Page plugins -->
  <!-- Argon CSS -->
  <link rel="stylesheet" href="/static/assets/css/argon.css?v=1.2.0"
        type="text/css">

  <!-- Specific CSS goes HERE -->
  {% block stylesheets %}{% endblock stylesheets %}

</head>

<body class="">

{% include "includes/sidenav.html" %}

<div class="main-content" id="panel">


  {% block content %}{% endblock content %}

</div>

{% include "includes/scripts.html" %}

<!-- Specific JS goes HERE -->
{% block javascripts %}{% endblock javascripts %}

<script src="/static/assets/js/argon.js?v=1.2.0"></script>

</body>

</html>

templates/tasks/tag_confirm_delete.html
{% extends 'layouts/base.html' %}
{% block title %}
  Confirm Deletion
{% endblock title %}

{% block content %}
  <div class="header pb-6 d-flex align-items-center"
       style="min-height: 300px; background-size: cover; background-position: center top;">
    <!-- Mask -->
    <span class="mask bg-gradient-default opacity-8"></span>
    <div class="container-fluid d-flex align-items-center">
      <div class="row" style="white-space: nowrap">
        <div class="col-lg-7 col-md-10">
          <h1 class="display-2 text-white">
            Confirm Deletion
          </h1>
        </div>
      </div>
    </div>
  </div>
  <!-- Page content -->
  <div class="container-fluid mt--9">
    <div class="row">
      <div class="col-xl-12 order-xl-1">
        <div class="card">
          <div class="card-body">
              <div class="pl-lg-4">
                <div class="row">
                  <h2 class="text-muted mb-4"
                      style="display: flex; justify-content: space-between; align-items: center;">
                    <p>
                      Are you sure you want to delete the tag?
                      <br>
                      <strong>"{{ tag.name }}"?</strong>
                    </p>
                  </h2>
                </div>
                <div class="card-body">
                  <form method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Delete
                    </button>
                    <a href="{{ referer }}"
                       class="btn btn-primary">Cancel</a>
                  </form>
                </div>
              </div>
        </div>
      </div>

    </div>
{% endblock content %}

templates/tasks/tag_form.html
{% extends 'layouts/base.html' %}
{% load crispy_forms_filters %}

{% block title %}
  {% if is_update %}
    Update the tag
  {% else %}
    Create a new tag
  {% endif %}
{% endblock title %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-xl-6">
      <div class="card">
        <div class="card-body">
          <h2 class="text-muted mb-4"
              style="display: flex; justify-content: space-between; align-items: center;">
            <strong>
              {% if is_update %}
                Update the tag
                {% if request.user.role == "Supervisor" %}
                  <a href="{% url 'tasks:delete-tag' tag.id %}?next={{ request.path }}"
                     class="btn btn-danger link-to-page">
                    Delete
                  </a>
                {% endif %}
              {% else %}
                Create a new tag
              {% endif %}
            </strong>
          </h2>
          <form action="" method="post" novalidate
                enctype="multipart/form-data" novalidate>
            {% csrf_token %}
            {{ form|crispy }}
            <div>
              <input type="submit" value="Save" class="btn btn-primary">
              <a href="{{ referer }}" class="btn btn-danger">Cancel</a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/tasks/tag_list.html
{% extends 'layouts/base.html' %}

{% block title %}My Tags{% endblock title %}

{% block content %}

  <div class="header pb-6 d-flex align-items-center"
       style="min-height: 300px; background-size: cover; background-position: center top;">
    <!-- Mask -->
    <span class="mask bg-gradient-default opacity-8"></span>
    <div class="container-fluid d-flex align-items-center">
      <div class="row" style="white-space: nowrap">
        <div class="col-lg-7 col-md-10">
          <h1 class="display-2 text-white">
            My Tags
          </h1>
        </div>
      </div>
    </div>
  </div>
  <!-- Page content -->
  <div class="container-fluid mt--9">
    <div class="row">
      <div class="col-xl-12 order-xl-1">
        <div class="card">
          <div class="card-body">
            <div class="pl-lg-4">
              <div class="row">
                <div class="container-fluid">
                  <div class="row">
                    <div class="col-lg-4 col-md-4 d-flex">
                      <a href="{% url 'tasks:add-tag' %}?next={{ request.path }}"
                         class="btn btn-success">
                        Add new Tag
                      </a>
                    </div>
                  </div>
                </div>
                {% if tag_list %}
                  <table class="table table-striped mt-4">
                    <tr class="text-center">
                      <th>Tag</th>
                      <th>Edite</th>
                      <th>Delete</th>
                    </tr>
                    {% for tag in tag_list %}
                      <tr class="text-center">
                      <td>{{ tag.name }}</td>
                      <td>
                        <a class="link-primary"
                           href="{% url 'tasks:update-tag' tag.id %}?next={{ request.path }}">
                          Edite
                        </a>
                      </td>
                      <td>
                        <a class="link-primary"
                           href="{% url 'tasks:delete-tag' tag.id %}?next={{ request.path }}">
                          Delete
                        </a>
                      </td>
                    {% endfor %}
                    </tr>
                  </table>
                {% else %}
                  <p>There are no tags.</p>
                {% endif %}
              </div>
              <hr class="my-4"/>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/tasks/task_confirm_delete.html
{% extends 'layouts/base.html' %}
{% block title %}
  Confirm Deletion
{% endblock title %}

{% block content %}
  <div class="header pb-6 d-flex align-items-center"
       style="min-height: 300px; background-size: cover; background-position: center top;">
    <!-- Mask -->
    <span class="mask bg-gradient-default opacity-8"></span>
    <div class="container-fluid d-flex align-items-center">
      <div class="row" style="white-space: nowrap">
        <div class="col-lg-7 col-md-10">
          <h1 class="display-2 text-white">
            Confirm Deletion
          </h1>
        </div>
      </div>
    </div>
  </div>
  <!-- Page content -->
  <div class="container-fluid mt--9">
    <div class="row">
      <div class="col-xl-12 order-xl-1">
        <div class="card">
          <div class="card-body">
              <div class="pl-lg-4">
                <div class="row">
                  <h2 class="text-muted mb-4"
                      style="display: flex; justify-content: space-between; align-items: center;">
                    <p>
                      Are you sure you want to delete the task?
                      <br>
                      <strong>"{{ task.name }}"</strong>
                    </p>
                  </h2>
                </div>
                <div class="card-body">
                  <form method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Delete
                    </button>
                    <a href="{% url 'tasks:my-tasks' %}"
                       class="btn btn-primary">Cancel</a>
                  </form>
                </div>
              </div>
        </div>
      </div>
    </div>
{% endblock content %}

templates/tasks/task_form.html
{% extends 'layouts/base.html' %}
{% load crispy_forms_filters %}

{% block title %}
  {% if is_update %}
    Update the task
  {% else %}
    Create a new task
  {% endif %}
{% endblock title %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-xl-6">
      <div class="card">
        <div class="card-body">
          <h2 class="text-muted mb-4"
              style="display: flex; justify-content: space-between; align-items: center;">
            <strong>
              {% if is_update %}
                Update the task
                {% if project.id %}
                  <a href="#"
                     class="btn btn-danger link-to-page">
                    Delete
                  </a>
                {% endif %}
              {% else %}
                Create a new task
              {% endif %}
            </strong>
          </h2>
          <form action="" method="post" novalidate
                enctype="multipart/form-data" novalidate>
            {% csrf_token %}
            {{ form|crispy }}
            <div class="pb-2">
              <a href="{% url 'tasks:add-tag' %}" class="btn btn-outline-success">
                Create a new tag
              </a>
            </div>
            <div>
              <input type="submit" value="Save" class="btn btn-primary">
              <a href="{{ referer }}" class="btn btn-danger">Cancel</a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/tasks/task_list.html
{% extends 'layouts/base.html' %}

{% block title %}My Tasks{% endblock title %}

{% block content %}

  <div class="header pb-6 d-flex align-items-center"
       style="min-height: 300px; background-size: cover; background-position: center top;">
    <!-- Mask -->
    <span class="mask bg-gradient-default opacity-8"></span>
    <div class="container-fluid d-flex align-items-center">
      <div class="row" style="white-space: nowrap">
        <div class="col-lg-7 col-md-10">
          <h1 class="display-2 text-white">
            My Tasks <a
              href="{% url 'tasks:add-task' %}?next={{ request.path }}"
              class="btn btn-success">Add</a>
          </h1>
        </div>
      </div>
    </div>
  </div>
  <!-- Page content -->
  <div class="container-fluid mt--9">
  <div class="row">
    <div class="col-xl-12 order-xl-1">
      <div class="card">
        <div class="card-body">
          <form>
            <div class="pl-lg-5">
              {% if task_list %}
                <table class="table table-bordered mt-4">
                  <thead>
                  <tr style="width: 20rem"></tr>
                  </thead>
                  <tbody class="table-group-divider">
                  <tr class="table-light">
                    {% for task in task_list %}
                      <td>
                        {% include "includes/task_card.html" %}
                      </td>
                      {% if forloop.counter|divisibleby:4 and not forloop.last %}
                        </tr>
                        <tr class="table-light">
                      {% endif %}
                    {% endfor %}
                    </tr>
                  </tbody>
                </table>
                <hr class="my-4"/>
              {% else %}
                <p>There are no tasks in the service.</p>
              {% endif %}
            </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}{% endblock javascripts %}